name: windowed_file_reader
description: A memory efficient sliding window file reader to read large files only at the places you want.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
