name: windowed_file_reader
description: An efficient file reader for reading large files utilizing a sliding window.
version: 1.0.3
repository: https://github.com/exoad/windowed_file_reader

environment:
    sdk: ^3.8.1

dev_dependencies:
    lints: ^5.0.0
    test: ^1.24.0
